// Generate a C source file that embeds a directory of frontend assets as one
// byte blob plus a lookup table, so the Windows host can serve the UI straight
// from the executable (no resources/ folder, no disk reads at runtime).
//
//   node scripts/embed-assets.mjs <srcDir> <outFile.c>
//
// Exposes a single C entry point consumed by native/webview2_host.cpp:
//   int keyparty_asset_lookup(const char *path,
//                             const unsigned char **data, size_t *len,
//                             const char **mime);
// `path` is the request path relative to the asset root (posix, no leading
// slash), e.g. "index.html" or "_next/static/chunks/app.js".

import { readdirSync, statSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";

const [, , srcDir, outFile] = process.argv;
if (!srcDir || !outFile) {
  console.error("usage: embed-assets.mjs <srcDir> <outFile.c>");
  process.exit(2);
}

const MIME = {
  html: "text/html; charset=utf-8",
  htm: "text/html; charset=utf-8",
  js: "text/javascript; charset=utf-8",
  mjs: "text/javascript; charset=utf-8",
  css: "text/css; charset=utf-8",
  json: "application/json; charset=utf-8",
  map: "application/json; charset=utf-8",
  txt: "text/plain; charset=utf-8",
  svg: "image/svg+xml",
  png: "image/png",
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  gif: "image/gif",
  ico: "image/x-icon",
  webp: "image/webp",
  woff: "font/woff",
  woff2: "font/woff2",
  ttf: "font/ttf",
  wasm: "application/wasm",
};
const mimeFor = (p) => MIME[p.split(".").pop().toLowerCase()] || "application/octet-stream";

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

const files = walk(srcDir).sort();
if (files.length === 0) {
  console.error(`embed-assets: no files under ${srcDir} — build the frontend first`);
  process.exit(1);
}
const entries = [];
const chunks = [];
let offset = 0;
for (const full of files) {
  const rel = relative(srcDir, full).split(sep).join("/");
  const bytes = readFileSync(full);
  entries.push({ path: rel, offset, len: bytes.length, mime: mimeFor(rel) });
  chunks.push(bytes);
  offset += bytes.length;
}
const blob = Buffer.concat(chunks);

// C string escape for the path/mime literals (ASCII-safe in practice, but be careful).
const cstr = (s) =>
  '"' + s.replace(/\\/g, "\\\\").replace(/"/g, '\\"') + '"';

const lines = [];
lines.push("/* Generated by scripts/embed-assets.mjs - do not edit. */");
lines.push("#include <stddef.h>");
lines.push("#include <string.h>");
lines.push("");
lines.push(`static const unsigned char kBlob[] = {`);
// Wrap the byte list so no single line gets pathologically long.
const PER_LINE = 40;
for (let i = 0; i < blob.length; i += PER_LINE) {
  let row = "";
  for (let j = i; j < Math.min(i + PER_LINE, blob.length); j++) row += blob[j] + ",";
  lines.push(row);
}
if (blob.length === 0) lines.push("0"); // a zero-length array is ill-formed in C
lines.push("};");
lines.push("");
lines.push("typedef struct { const char *path; size_t offset; size_t len; const char *mime; } Entry;");
lines.push("static const Entry kEntries[] = {");
for (const e of entries) {
  lines.push(`  { ${cstr(e.path)}, ${e.offset}, ${e.len}, ${cstr(e.mime)} },`);
}
lines.push("};");
lines.push(`static const size_t kEntryCount = ${entries.length};`);
lines.push("");
lines.push("int keyparty_asset_lookup(const char *path, const unsigned char **data, size_t *len, const char **mime) {");
lines.push("    size_t i;");
lines.push("    for (i = 0; i < kEntryCount; i++) {");
lines.push("        if (strcmp(path, kEntries[i].path) == 0) {");
lines.push("            *data = kBlob + kEntries[i].offset;");
lines.push("            *len = kEntries[i].len;");
lines.push("            *mime = kEntries[i].mime;");
lines.push("            return 1;");
lines.push("        }");
lines.push("    }");
lines.push("    return 0;");
lines.push("}");
lines.push("");

writeFileSync(outFile, lines.join("\n"));
console.error(`embed-assets: ${entries.length} files, ${blob.length} bytes -> ${outFile}`);
